# basic compose structure

networks:
  db:
    
services:
  db:
    container_name: person-db
    environment:
      PGPASSWORD:        "${DB_PASSWORD:?}"
      POSTGRES_DB:       "${DB_NAME:?}"
      POSTGRES_PASSWORD: "${DB_PASSWORD:?}"
      POSTGRES_USER:     "${DB_USERNAME:?}"
      TZ:                "Europe/Moscow"
    expose:
      - 5432
    healthcheck:
      interval: 3s
      retries: 2
      start_period: 5s
      test: [ "CMD", "pg_isready", "-q", "-d", "${DB_NAME:?}", "-U", "${DB_USERNAME}" ]
      timeout: 3s
    networks:
      - db
    profiles:
      - prod
      - dev
      - db-test
    volumes:
      - ./postgres/init:/docker-entrypoint-initdb.d:ro

  db-migrate:
    command: -path /migrations/ -database postgres://${DB_USERNAME:?}:${DB_PASSWORD:?}@db:5432/${DB_NAME:?}?sslmode=disable up
    container_name: person-migrate
    depends_on:
      db:
        condition: service_healthy
        restart: true
    image: migrate/migrate:4
    networks:
      - db
    profiles:
      # no need to run for db-test - the test image runs migrations on its own
      - prod
      - dev
