# override for development

services:
  db:
    command: ["postgres", "-c", "log_statement=all"]
    image: postgres:16-alpine
    ports:
      - 5432:5432
    volumes:
      - db-dev:/var/lib/postgresql/data

  db-migrate:
    volumes:
      - ./postgres/migrations:/migrations

volumes:
  db-dev:
