// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.16.2 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
)

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/9RYbW/jNhL+KwSvwKWAbDmOE9zqW7ppCxf7Emw2d8UFucVYGllsKVIlKTdGoP9+ICnL",
	"UiTFTje4w36KFb7MM+8P55HGMi+kQGE0jR5pAQpyNKj8FyotxfLK/k5Qx4oVhklBI7q8IjIlJkNy7fbQ",
	"gDL7/wJMRgMqIEf7tTsfUIV/lExhQiOjSgyojjPMwV78ncKURvRv4R5J6Fd1eHu7vKJVVdnzupBCo8O1",
	"mC0+SPOTLEXSh+YBkT+ZyRxAXWDMUoYJWV6RP0ETIQ1J3dkqoOe//roUBpUAfoNqg+pHpaQaULjeRLTb",
	"RdBts8hqrPbI5RrtH3yAvOBIo8U8oDk8sLzMaXQ6Pw9ozoT/mgXUbAtrJCYMrlFZMG9lKYzavpUJ9hHU",
	"iySWCZLVlixvPpKz04uLySkBXmQwmdNgL5p+uqVO+DsUa5PRaO6Et74KMFYlGtH/3F1O/n3/OK++ow0q",
	"bRQTawvqGtZMgAXxMU01mncsZ8ZFh5IFKsO8T+JSKRTmC98tP6/qbrt0dx7eb6QB/oUZzPWhzVU72u6e",
	"AOtJ7l5931wnV79hbJwBXED9ABr7WvtAb7mcXuXMKLalHXOfDti1AKOk2OYs7l7wT9CM44bF2ZA3dKn6",
	"Mm91Br/LzSGZ1ahyP5Wc2yuB848pje6ez0p/5hqUYcBpFTx27O3g7YF2FA0orNHVBxtPwJmxhtL4MGD4",
	"+w66fzGT+UL0EoxOLwuw6zWWHFl4upHEkmdhXsN6IEKKJn0OyRxONBspKJ2fH2kT/8epXhtt73dQCrY9",
	"vVoQG2HjibDz+wtd4fKn74raZs+dt1W16sbMgRPtOlr5+Dpw4gYfhvKj5VypzRUY+MtqD6RIJzF2+TIc",
	"YTdeBRS25t3RHLi9IEX3475d9+ulXuFwEd2pGvHZWbqAeDFZnJ3DZHGRnk5W8/n55PzN+cXqNH4Tz+Pz",
	"bg85u+hUGPvZ7iKzyRuYpPeP/6gmze/FEb9PhzpPQB8mazmp/1mWLJk6FVr/n7C8kMr3Iss7IrpmJitX",
	"01jm4VrKNcfQHrQMorIEJZX9tvo5Y5owTYAY1IYUSlqrk1Qq8mOaYmzYBt/LFXNW5SxG4ftATXHeLz/T",
	"gJaK04hmxhQ6CkNZoNCyVDFOpVqH9aEwZyZ0uciMs78PEOBLkUpyeb2kAd2g0h7WbDqbzuxuexkUjEb0",
	"bDqbnvmwyVzuhJ5f2Z9r30NtZrk0WSaNgHdMG3dqz+zuhjnT3zWxWpGTGDROmNAoNLP6B0SznHFQzGyJ",
	"RlBx9v2O8f1RotruKd+u+jf07kBHGkVS58NXgdn3oL+OB5SxVLfBtU/ao6AFBPPCbF08Cdk6PYa5WxQa",
	"2AeBvveMyAlqwPpuOyQG1vglZ4Iey8RdER6Q6tnti6TCw9dKbYVr0xPISZ8QO648HqkdDnIUnk5jeS54",
	"8WEsJPF47eum1K9YCnUmeeKs3os4cjKbzoiR5HQ6G9Pd7K7oYEkwhZIbGs2m5+2Hy+CzRZT5yrPtPj4k",
	"ftUmjsJYqkRbQPp3VowAasj4EJrgAN0fB6CfIFBoSiXICXBOWEpG7bN7KwygmR+Cc//ksTqfzdz7SAqD",
	"wlVpKArOYhd+4W91AT8uIlpE07W0rt6XpIA17quVbR8LL/3pY3YDnCXEaU1ancE/iMdQNGqFI69m9xwu",
	"8xzUlkbUNp4ayc4Hjs1KPdqrLMuqhwWozQ8y2b626XY0ruqSYKNKrHqOO3016ftBxvCwAjSJFYLBhOgy",
	"jlHrtOR8e9CD9flUqhwcR1/M56MjEddPNWLucmGFhPlbnNtnZwPcCC3BAsX4lpQCNsBh5XhQhpDUM6JP",
	"aNR2cpkaVF1zdK/60BQEjbEUiSalMIy7CU2OJpMJWWEsc9QENsB2gp7NtOpVw/Wtsz+BJnmqYMewwsfd",
	"JKvymnE0OBbDV361x7iGIO63hM2sbKyAjAaOh3Nk4Hx+OhFjfiAGxAeUD1R7eHHYru053Kv6wtuw8QVZ",
	"bYkP02d47s9oXt/or1h62g/yfiH43IxS/eRy7yOv+DfszJ/RDHiyABNno33ALX6lN1/SQ+pXcXuKuwFe",
	"YjOiWFxYpXZzsqdrDXH4RWbiyXwrorc33cd+ROuhV/Nab6Z69C0KcPb7ADleiuRmP+9rhHZl9c5WwQvZ",
	"RD3HO6YjPl+JyiJ5jRb2f43WW6cDAUuLWi8/crJhQH65+fiBvEe1RuJC9HsXyeU4nynN/zKKX1qOXsPn",
	"CgsO8Tfu9E9eiXbzd3NDu39oXvJOxsDrmc1+9hOFIbcLmdQmhIKFmxmt7qv/BgAA//8i3v3FZBsAAA==",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
